/**
 * 报告文案多语言表（阶段四 i18n）
 *
 * 默认中文；--lang en 输出英文卡片（面向海外社区分享）。
 * 品牌名（DSH / Claude Code / Dev Wrapped）与统计数字本身不翻译。
 * 占位符格式 {name}，由 t() 替换。
 */

/** 支持的语言 */
export type Lang = 'zh' | 'en'

/** 中文文案表（键的唯一权威定义处，英文表必须与之对齐） */
const zh = {
  /* ---------- 标题与时间范围 ---------- */
  yearTitle: '{year} 年度回顾',
  rangeDays: '{n} 天',
  /* ---------- 核心数字 ---------- */
  statSessions: '会话总数',
  statTurns: '对话轮数',
  statToolCalls: '工具调用',
  statActiveDays: '活跃天数',
  /* ---------- 工具排行 ---------- */
  toolRankTitle: '🛠️ 工具排行',
  toolRankSub: 'TOP8（含 {n} 次调用）',
  noToolData: '暂无工具调用数据',
  /* ---------- 小时分布 ---------- */
  hourlyTitle: '24 小时活跃分布',
  peakLabel: '高峰时段 {hh}:00',
  noData: '无数据',
  /* ---------- 亮点 ---------- */
  highlightsTitle: '✨ 你的开发亮点',
  favoriteTool: '最爱工具',
  favoriteWorkspace: '最爱项目',
  longestSession: '最长会话',
  mostComplexTask: '最复杂任务',
  /* ---------- 更多数据 ---------- */
  moreDataTitle: '📊 更多数据',
  userMessages: '用户消息',
  tokenUsage: 'Token 用量',
  tokensIn: '输入',
  tokensOut: '输出',
  tokensMissing: '部分会话缺少用量记录',
  costEstimate: '成本估算',
  costEstimateNote: '估算值 · 按 {model} 单价（输入 ¥{in}/M、输出 ¥{out}/M）',
  filesRead: '读取文件（去重）',
  filesWritten: '写入文件（去重）',
  peakDay: '最活跃的一天',
  topExts: '常打交道扩展名',
  /* ---------- 热门会话 ---------- */
  topSessionsTitle: '🏆 热门会话 TOP5',
  thProject: '项目',
  thStart: '开始时间',
  thTurns: '轮次',
  thToolCalls: '工具调用',
  thTopTools: '常用工具',
  /* ---------- 单位 ---------- */
  unitCalls: '次调用',
  unitToolCalls: '次工具调用',
  unitTurns: '轮',
  unitSteps: '步',
  unitToolsKinds: '种工具',
  unitDay: '天',
  unitHour: '小时',
  unitMinute: '分钟',
  /* ---------- 页脚 ---------- */
  footerGeneratedBy: '由 dsh-dev-wrapped 生成',
  footerDataFrom: '数据 100% 来自本地{source}会话记录',
  dataSourceDsh: 'DSH',
  dataSourceClaude: 'Claude Code',
  /* ---------- story 叙事屏 ---------- */
  storyScrollHint: '向下滚动开启回顾 ↓',
  storySessionsLead: '这段时间你开启了',
  storySessionsTail: '个 AI 结对编程会话',
  storyToolCallsLead: '一共发起了',
  storyToolCallsTail: '次工具调用',
  storyFavToolLead: '你的最爱工具是',
  storyFavToolTimes: '共 {n} 次',
  storyPeakLead: '你的代码高峰出现在',
  storyPeakTail: '点',
  storyLongestLead: '最长的一次会话持续了',
  storyLongestSub: '{tools} 次工具调用 · {turns} 轮 · {workspace}',
  storyWorkspaceLead: '你最常奋战的项目是',
  storyWorkspaceCalls: '{n} 次工具调用',
  storyTokenLead: '模型为你处理了',
  storyTokenSub: '{in} 输入 · {out} 输出',
  storyFinalLead: '你在 {n} 个日子里与 AI 并肩作战',
  storyFinalSub: '期待下一段旅程 ✨',
  /* ---------- 其他 ---------- */
  empty: '—',
}

/** 英文文案表（键集合与 zh 完全一致） */
const en: Record<keyof typeof zh, string> = {
  /* ---------- 标题与时间范围 ---------- */
  yearTitle: '{year} Year in Review',
  rangeDays: '{n} days',
  /* ---------- 核心数字 ---------- */
  statSessions: 'Sessions',
  statTurns: 'Turns',
  statToolCalls: 'Tool Calls',
  statActiveDays: 'Active Days',
  /* ---------- 工具排行 ---------- */
  toolRankTitle: '🛠️ Tool Ranking',
  toolRankSub: 'TOP8 ({n} calls)',
  noToolData: 'No tool call data',
  /* ---------- 小时分布 ---------- */
  hourlyTitle: 'Activity by Hour',
  peakLabel: 'Peak at {hh}:00',
  noData: 'No data',
  /* ---------- 亮点 ---------- */
  highlightsTitle: '✨ Your Highlights',
  favoriteTool: 'Favorite Tool',
  favoriteWorkspace: 'Favorite Project',
  longestSession: 'Longest Session',
  mostComplexTask: 'Most Complex Task',
  /* ---------- 更多数据 ---------- */
  moreDataTitle: '📊 More Stats',
  userMessages: 'User Messages',
  tokenUsage: 'Token Usage',
  tokensIn: 'in',
  tokensOut: 'out',
  tokensMissing: 'Some sessions lack usage data',
  costEstimate: 'Cost Estimate',
  costEstimateNote: 'Estimated · {model} pricing (¥{in}/M in, ¥{out}/M out)',
  filesRead: 'Files Read (unique)',
  filesWritten: 'Files Written (unique)',
  peakDay: 'Busiest Day',
  topExts: 'Top File Types',
  /* ---------- 热门会话 ---------- */
  topSessionsTitle: '🏆 Top Sessions',
  thProject: 'Project',
  thStart: 'Started',
  thTurns: 'Turns',
  thToolCalls: 'Tool Calls',
  thTopTools: 'Top Tools',
  /* ---------- 单位 ---------- */
  unitCalls: 'calls',
  unitToolCalls: 'tool calls',
  unitTurns: 'turns',
  unitSteps: 'steps',
  unitToolsKinds: 'tools',
  unitDay: 'd',
  unitHour: 'h',
  unitMinute: 'm',
  /* ---------- 页脚 ---------- */
  footerGeneratedBy: 'Generated by dsh-dev-wrapped',
  footerDataFrom: 'Data 100% from local {source} session logs',
  dataSourceDsh: 'DSH',
  dataSourceClaude: 'Claude Code',
  /* ---------- story 叙事屏 ---------- */
  storyScrollHint: 'Scroll to start your review ↓',
  storySessionsLead: 'During this period you started',
  storySessionsTail: 'AI pair-programming sessions',
  storyToolCallsLead: 'You made a total of',
  storyToolCallsTail: 'tool calls',
  storyFavToolLead: 'Your favorite tool is',
  storyFavToolTimes: '{n} times',
  storyPeakLead: 'Your coding peak hits at',
  storyPeakTail:":00",
  storyLongestLead: 'Your longest session lasted',
  storyLongestSub: '{tools} tool calls · {turns} turns · {workspace}',
  storyWorkspaceLead: 'Your home project is',
  storyWorkspaceCalls: '{n} tool calls',
  storyTokenLead: 'The model processed for you',
  storyTokenSub: '{in} in · {out} out',
  storyFinalLead: 'You coded with AI on {n} days',
  storyFinalSub: 'See you next journey ✨',
  /* ---------- 其他 ---------- */
  empty: '—',
}

/** 文案表：语言 → 键 → 文案 */
export const STRINGS: Record<Lang, Record<string, string>> = { zh, en }

/**
 * 取文案并替换 {name} 占位符。
 * 未知键返回键名本身（开发期显式暴露问题，不静默空串）。
 */
export function t(lang: Lang, key: keyof typeof zh, params?: Record<string, string | number>): string {
  let text: string = STRINGS[lang][key] ?? STRINGS.zh[key] ?? String(key)
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replaceAll(`{${k}}`, String(v))
    }
  }
  return text
}
